spring.application.name=wsRestaurante
server.servlet.context-path=/restaurante/service/api
# SERVIDOR - Puerto de desarrollo
server.port=8080
# JACKSON - Zona horaria y formato de fechas
spring.jackson.time-zone=America/Lima
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.sql.init.mode=never
# DATASOURCE - Configuración específica de DEV
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=BD_RESTAURANTE
spring.datasource.password=Pass1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# HIKARI - Pool conexiones
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
# SPRINT BOOT ACTUATOR - Habilitar todos los endpoints
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
# Info del app visible en /actuator/info
info.app.name=wsRestaurante
info.app.version=0.0.1
info.app.description=API REST Restaurante
# SWAGGER/OPENAPI - Configuración común
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.packages-to-scan=com.jhontruse.wsrestaurante.controller
springdoc.paths-to-match=/**
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
# CORS - Configuración común
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=*
app.cors.allow-credentials=true
# LOGGING - Nivel DEBUG para desarrollo
logging.level.root=INFO
logging.level.com.jhontruse.wsrestaurante=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# JWT - SECRET y tiempos de expiración
security.jwt.key=wsr_authentication_service_KEY
security.jwt.secret-base64=Nr1RzuxLf4cAjVzMU5PLVx6kDYdmN6FD56VAq2Hn/mA=
security.jwt.secret.key=$2a$12$.qy.6yn0geTRmkwaaPaJMewc72nlyfwPjwgGB.4SjEbfTYElPUavi
security.jwt.issuer=ws_restaurante_service
security.jwt.max-attempts=5
security.jwt.temp-lock-minutes=5
security.jwt.expiration=1800000
security.jwt.refresh.expiration=864000000
# Permite que primitivos reciban null sin lanzar excepción
spring.jackson.deserialization.fail-on-null-for-primitives=false